repos:
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: python
      types: [python]
      additional_dependencies:
        - pylint

    - id: coverage
      name: run test coverage
      entry: bash
      language: python
      stages: [pre-push]
      pass_filenames: false
      additional_dependencies:
        - coverage
        - pytest
      args:
        - -c
        - |
          coverage run -m pytest
          coverage report
